create table PESSOA (
CODIGO_PESSOA        INT8                 not null,
CODIGO_ALUNO         INT8                 null,
CODIGO_PROFESSOR     INT8                 null,
CODIGO_ENDERECO      INT8                 null,
CODIGO_FUNCIONARIO   INT8                 null,
NOME_PESSOA          VARCHAR(50)          null,
CPF                  VARCHAR(14)          null,
IDENTIDADE           VARCHAR(14)          null,
TELEFONE             VARCHAR(30)          null,
CELULAR              VARCHAR(50)          null,
DATA_NASCIMENTO      DATE                 null,
EMAIL                VARCHAR(50)          null,
TIPO_PESSOA          CHAR(1)              null,
SEXO                 VARCHAR(50)          null,
OBSERVACAO           TEXT                 null,
NOME_PAI             VARCHAR(50)          null,
NOME_MAE             VARCHAR(50)          null,
NOME_RESPONSAVEL     VARCHAR(50)          null
);